### ISSUE TITLE
"knex migrate:latest && node Main.js fetch all" failing

### ISSUE THREAD

**Issue by jmstein** [robgraeber/financial-scraper#1]
Hi Rob,

Sorry to bug you. Do you have an example of what the connection string should look like? I installed PG and poked around the knex docs a bit, but I'm getting "There is no pool defined on the current client" when I try to migrate:latest. I figured you might have an example that we could add to the README.

Thanks!

**Comment by robgraeber** [comment]
Hey dude, sure the connection string looks like: ‘postgres://username:password@db.asdf.us-east-1.rds.amazonaws.com/databasename’
